// integrations/flexor_integration.jsx
import React, { useEffect, useRef } from 'react';
import Flexor from './flexor.js';

const FlexorContainer = ({ children, config, ...props }) => {
  const ref = useRef(null);

  useEffect(() => {
    if (ref.current) {
      const dataFlexor = Flexor.generateConfig({ mode: 'flex', ...config });
      ref.current.setAttribute('data-flexor', dataFlexor);
      Flexor.applyTo(ref.current);
    }
  }, [config]);

  return <div ref={ref} {...props}>{children}</div>;
};

// Usage
export default function App() {
  return (
    <FlexorContainer config={{ direction: 'row', gap: '10px', smart: true }}>
      <div>Item 1</div>
      <div>Item 2 with more text</div>
      <div>Item 3</div>
    </FlexorContainer>
  );
}

// integrations/flexor_integration.vue
<template>
    <div ref="container" :data-flexor="generatedConfig" v-bind="$attrs">
      <slot></slot>
    </div>
  </template>
  
  <script>
  import { defineComponent, ref, computed, onMounted } from 'vue';
  import Flexor from './flexor.js';
  
  export default defineComponent({
    name: 'FlexorContainer',
    props: ['config'],
    setup(props) {
      const container = ref(null);
      const generatedConfig = computed(() => Flexor.generateConfig({ mode: 'flex', ...props.config }));
  
      onMounted(() => {
        if (container.value) {
          Flexor.applyTo(container.value);
        }
      });
  
      return { container, generatedConfig };
    }
  });
  </script>
  
  <!-- Usage -->
  <template>
    <flexor-container :config="{ direction: 'row', gap: '10px', smart: true }">
      <div>Item 1</div>
      <div>Item 2 with more text</div>
      <div>Item 3</div>
    </flexor-container>
  </template>
